# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUZ71oG11iwNKH-svH29-Nt3rxcMPPrN

# Exercice 1 — Portes logiques AND et OR

### Implémentation 1 : From Scratch
"""

import numpy as np

# Fonction d'activation (step function)
def activation(x):
    return 1 if x >= 0 else 0

# Entraînement du perceptron
def train_perceptron(X, y, epochs=10, lr=0.1):
    weights = np.zeros(len(X[0]))
    bias = 0

    for _ in range(epochs):
        for i in range(len(X)):
            linear_output = np.dot(X[i], weights) + bias
            y_pred = activation(linear_output)

            # mise à jour
            error = y[i] - y_pred
            weights += lr * error * X[i]
            bias += lr * error

    return weights, bias

# Prédiction
def predict(X, weights, bias):
    y_pred = []
    for x in X:
        linear_output = np.dot(x, weights) + bias
        y_pred.append(activation(linear_output))
    return y_pred


# Données
X = np.array([[0,0], [0,1], [1,0], [1,1]])

y_and = np.array([0,0,0,1])
y_or  = np.array([0,1,1,1])

# AND
w_and, b_and = train_perceptron(X, y_and)
print("AND predictions:", predict(X, w_and, b_and))

# OR
w_or, b_or = train_perceptron(X, y_or)
print("OR predictions:", predict(X, w_or, b_or))

"""### Implémentation 2 : Scikit-learn

"""

from sklearn.linear_model import Perceptron
import numpy as np

# Données
X = np.array([[0,0], [0,1], [1,0], [1,1]])

y_and = np.array([0,0,0,1])
y_or  = np.array([0,1,1,1])

# AND
model_and = Perceptron()
model_and.fit(X, y_and)
print("AND predictions:", model_and.predict(X))

# OR
model_or = Perceptron()
model_or.fit(X, y_or)
print("OR predictions:", model_or.predict(X))

"""### Implémentation 3 : Keras

"""

import numpy as np
from tensorflow import keras

X     = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)
y_and = np.array([0, 0, 0, 1], dtype=float)
y_or  = np.array([0, 1, 1, 1], dtype=float)

def create_model():
    model = keras.Sequential([
        keras.layers.Dense(1, activation='sigmoid', input_shape=(2,))
    ])
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.1),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

# AND
model_and = create_model()
model_and.fit(X, y_and, epochs=1000, verbose=0)
pred_and = (model_and.predict(X) > 0.5).astype(int).flatten()
print("AND predictions:", pred_and)
print("AND attendu    :", y_and.astype(int))

# OR
model_or = create_model()
model_or.fit(X, y_or, epochs=1000, verbose=0)
pred_or = (model_or.predict(X) > 0.5).astype(int).flatten()
print("\nOR predictions:", pred_or)
print("OR attendu    :", y_or.astype(int))

"""EXERCICE 2 :

Version FROM SCRATCH
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Charger données
iris = load_iris()
X = iris.data[:, 2:4]
y = (iris.target == 0).astype(int)

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Activation
def activation(x):
    return 1 if x >= 0 else 0

# Training
def train(X, y, epochs=20, lr=0.01):
    weights = np.zeros(X.shape[1])
    bias = 0

    for _ in range(epochs):
        for i in range(len(X)):
            linear = np.dot(X[i], weights) + bias
            y_pred = activation(linear)

            error = y[i] - y_pred
            weights += lr * error * X[i]
            bias += lr * error

    return weights, bias

# Predict
def predict(X, w, b):
    preds = []
    for x in X:
        preds.append(activation(np.dot(x, w) + b))
    return np.array(preds)

# Train
w, b = train(X_train, y_train)

# Test
y_pred = predict(X_test, w, b)

# Accuracy
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

"""Version avec scikit-learn"""

from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# Charger données
iris = load_iris()
X = iris.data[:, 2:4]  # longueur & largeur pétale
y = (iris.target == 0).astype(int)  # Setosa = 1, autres = 0

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Modèle
model = Perceptron()
model.fit(X_train, y_train)

# Prédiction
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

"""Version avec Keras"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow import keras
import numpy as np

# ── 1. Charger les données ─────────────────────────────────
iris = load_iris()
X = iris.data[:, 2:4]          # longueur et largeur des pétales
y = (iris.target == 0).astype(int)   # 1 = Setosa, 0 = autres

# ── 2. Normalisation ✅ (c'était manquant !) ───────────────
scaler = StandardScaler()
X = scaler.fit_transform(X)    # met les données à la même échelle

# ── 3. Split train/test ────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ── 4. Modèle Keras ───────────────────────────────────────
model = keras.Sequential([
    keras.layers.Dense(1, activation='sigmoid', input_shape=(2,))
])
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ── 5. Entraînement ───────────────────────────────────────
model.fit(X_train, y_train, epochs=200, verbose=0)  # ✅ 200 epochs

# ── 6. Évaluation ─────────────────────────────────────────
y_pred = (model.predict(X_test) > 0.5).astype(int).flatten()
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy Keras : {acc:.4f}")   # attendu : 1.0 ou 0.9667

"""EXERCICE 3

Implémentation 1 — From Scratch
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# ── 1. Créer les données y = 2x + 1 ───────────────────────
np.random.seed(42)
X = np.linspace(0, 10, 100)                    # 100 valeurs de 0 à 10
y = 2 * X + 1 + np.random.randn(100) * 0.5    # y=2x+1 + bruit léger

# ── 2. Split train/test ────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ── 3. Perceptron Régression From Scratch ─────────────────
class PerceptronRegression:
    def __init__(self, lr=0.001, epochs=1000):
        self.lr     = lr
        self.epochs = epochs
        self.w      = 0.0
        self.b      = 0.0

    def predict(self, X):
        return self.w * X + self.b      # pas de fonction seuil !

    def fit(self, X, y):
        for _ in range(self.epochs):
            for xi, yi in zip(X, y):
                y_pred  = self.predict(xi)
                error   = yi - y_pred
                self.w += self.lr * error * xi
                self.b += self.lr * error
        return self

# ── 4. Entraînement ───────────────────────────────────────
model = PerceptronRegression(lr=0.001, epochs=1000)
model.fit(X_train, y_train)

# ── 5. Évaluation MSE ─────────────────────────────────────
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"From Scratch — MSE : {mse:.4f}")
print(f"Poids appris  : w = {model.w:.4f}, b = {model.b:.4f}")
# attendu : w ≈ 2.0, b ≈ 1.0

# ── 6. Visualisation ──────────────────────────────────────
plt.figure(figsize=(8, 5))
plt.scatter(X_test, y_test, color='steelblue', label='Données réelles', alpha=0.7)
plt.plot(X_test, y_pred, color='red', linewidth=2, label=f'Prédiction (MSE={mse:.4f})')
plt.xlabel("x")
plt.ylabel("y")
plt.title("Régression linéaire — From Scratch")
plt.legend()
plt.savefig("ex3_scratch.png", dpi=150)
plt.show()

"""Implémentation 2 — Scikit-learn

"""

from sklearn.linear_model import Perceptron
from sklearn.metrics import mean_squared_error

# Scikit-learn Perceptron ne fait pas de régression directement
# On utilise SGDRegressor qui est l'équivalent
from sklearn.linear_model import SGDRegressor

model_sk = SGDRegressor(max_iter=1000, learning_rate='constant',
                        eta0=0.001, random_state=42)
model_sk.fit(X_train.reshape(-1,1), y_train)

y_pred_sk = model_sk.predict(X_test.reshape(-1,1))
mse_sk = mean_squared_error(y_test, y_pred_sk)
print(f"Scikit-learn — MSE : {mse_sk:.4f}")

"""Implémentation 3 — Keras

"""

from tensorflow import keras
import numpy as np

model_keras = keras.Sequential([
    keras.layers.Dense(1, activation='linear', input_shape=(1,))  # linear pour régression
])
model_keras.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse',          # Mean Squared Error
    metrics=['mse']
)
model_keras.fit(X_train.reshape(-1,1), y_train, epochs=200, verbose=0)

y_pred_keras = model_keras.predict(X_test.reshape(-1,1)).flatten()
mse_keras = mean_squared_error(y_test, y_pred_keras)
print(f"Keras — MSE : {mse_keras:.4f}")

"""EXERCICE 4

Implémentation 1 — From Scratch
"""

import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ── 1. Charger MNIST (sous-ensemble pour simplifier) ──────
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target.astype(int)

# On prend seulement 5000 exemples pour aller plus vite
X, y = X[:5000], y[:5000]

# ── 2. Normaliser (0-255 → 0-1) ───────────────────────────
X = X / 255.0

# ── 3. Split train/test ────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ── 4. Perceptron From Scratch (One-vs-All) ───────────────
# Pour 10 classes, on crée 10 perceptrons (un par chiffre)
class PerceptronMultiClasse:
    def __init__(self, lr=0.01, epochs=10):
        self.lr     = lr
        self.epochs = epochs

    def fit(self, X, y, n_classes=10):
        n_features   = X.shape[1]
        self.weights = np.zeros((n_classes, n_features))
        self.biases  = np.zeros(n_classes)

        for _ in range(self.epochs):
            for xi, yi in zip(X, y):
                scores = np.dot(self.weights, xi) + self.biases
                y_pred = np.argmax(scores)
                if y_pred != yi:
                    self.weights[yi] += self.lr * xi
                    self.biases[yi]  += self.lr
                    self.weights[y_pred] -= self.lr * xi
                    self.biases[y_pred]  -= self.lr
        return self

    def predict(self, X):
        scores = np.dot(X, self.weights.T) + self.biases
        return np.argmax(scores, axis=1)

# ── 5. Entraînement et évaluation ─────────────────────────
model_scratch = PerceptronMultiClasse(lr=0.01, epochs=10)
model_scratch.fit(X_train, y_train)

y_pred = model_scratch.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"From Scratch — Accuracy : {acc:.4f}")

"""Implémentation 2 — Scikit-learn

"""

from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

model_sk = Perceptron(max_iter=50, random_state=42)
model_sk.fit(X_train, y_train)

y_pred_sk = model_sk.predict(X_test)
acc_sk = accuracy_score(y_test, y_pred_sk)
print(f"Scikit-learn — Accuracy : {acc_sk:.4f}")

"""Implémentation 3 — Keras

"""

from tensorflow import keras
import numpy as np

# ── Modèle ────────────────────────────────────────────────
model_keras = keras.Sequential([
    keras.layers.Dense(10, activation='softmax', input_shape=(784,))
    # softmax car 10 classes (0 à 9)
])
model_keras.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='sparse_categorical_crossentropy',  # pour multi-classes
    metrics=['accuracy']
)

# ── Entraînement ──────────────────────────────────────────
model_keras.fit(X_train, y_train, epochs=20, verbose=0)

# ── Évaluation ────────────────────────────────────────────
loss, acc_keras = model_keras.evaluate(X_test, y_test, verbose=0)
print(f"Keras — Accuracy : {acc_keras:.4f}")

"""EXERCICE 5

Implémentation 1 — From Scratch
"""

"""
Exercice 5 - Implémentation FROM SCRATCH
Segmentation des données synthétiques avec le Perceptron
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# ─────────────────────────────────────────
# 1. Génération des données
# ─────────────────────────────────────────
X, y = make_blobs(n_samples=300, centers=3, random_state=42, cluster_std=1.2)

plt.figure(figsize=(6, 4))
colors = ['red', 'blue', 'green']
for i in range(3):
    plt.scatter(X[y == i, 0], X[y == i, 1], c=colors[i], label=f'Cluster {i}', edgecolors='k')
plt.title("Nuage de points - Données initiales (3 clusters)")
plt.legend()
plt.tight_layout()
plt.savefig("ex5_scratch_data.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# 2. Prétraitement : on garde clusters 0 et 1 (binaire)
# ─────────────────────────────────────────
mask = y != 2
X_bin = X[mask]
y_bin = y[mask]

scaler = StandardScaler()
X_bin_scaled = scaler.fit_transform(X_bin)

X_train, X_test, y_train, y_test = train_test_split(
    X_bin_scaled, y_bin, test_size=0.2, random_state=42
)

# ─────────────────────────────────────────
# 3. Perceptron FROM SCRATCH
# ─────────────────────────────────────────
class PerceptronScratch:
    def __init__(self, lr=0.01, n_epochs=100):
        self.lr = lr
        self.n_epochs = n_epochs
        self.weights = None
        self.bias = None

    def _step(self, z):
        return np.where(z >= 0, 1, 0)

    def fit(self, X, y):
        n_samples, n_features = X.shape
        # i. Initialisation des poids et du biais
        self.weights = np.zeros(n_features)
        self.bias = 0
        self.errors_ = []

        for _ in range(self.n_epochs):
            errors = 0
            for xi, yi in zip(X, y):
                # ii. Calcul de la sortie
                z = np.dot(xi, self.weights) + self.bias
                y_pred = self._step(z)
                # iii. Mise à jour des poids
                update = self.lr * (yi - y_pred)
                self.weights += update * xi
                self.bias    += update
                errors += int(update != 0)
            self.errors_.append(errors)

    def predict(self, X):
        z = np.dot(X, self.weights) + self.bias
        return self._step(z)

    def accuracy(self, X, y):
        return np.mean(self.predict(X) == y)


perceptron = PerceptronScratch(lr=0.01, n_epochs=50)
perceptron.fit(X_train, y_train)

acc = perceptron.accuracy(X_test, y_test)
print(f"[From Scratch] Accuracy sur le test : {acc * 100:.2f}%")

# Courbe d'erreurs
plt.figure(figsize=(6, 3))
plt.plot(range(1, len(perceptron.errors_) + 1), perceptron.errors_, marker='o')
plt.title("Évolution des erreurs - From Scratch")
plt.xlabel("Époque")
plt.ylabel("Nombre d'erreurs")
plt.tight_layout()
plt.savefig("ex5_scratch_errors.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# Visualisation de la frontière de décision
# ─────────────────────────────────────────
def plot_decision_boundary(model, X, y, title, filename, mode='scratch'):
    x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                         np.linspace(y_min, y_max, 200))
    grid = np.c_[xx.ravel(), yy.ravel()]

    if mode == 'scratch':
        Z = model.predict(grid)
    else:
        Z = model.predict(grid)

    Z = Z.reshape(xx.shape)
    plt.figure(figsize=(6, 4))
    plt.contourf(xx, yy, Z, alpha=0.3, cmap='bwr')
    for i, c in enumerate(['red', 'blue']):
        plt.scatter(X[y == i, 0], X[y == i, 1], c=c, edgecolors='k', label=f'Cluster {i}')
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=100)
    plt.show()

plot_decision_boundary(perceptron, X_test, y_test,
                       "Frontière de décision - From Scratch",
                       "ex5_scratch_boundary.png", mode='scratch')

"""Implémentation 2 — Scikit-learn

"""

"""
Exercice 5 - Implémentation SCIKIT-LEARN
Segmentation des données synthétiques avec le Perceptron
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, classification_report

# ─────────────────────────────────────────
# 1. Génération des données
# ─────────────────────────────────────────
X, y = make_blobs(n_samples=300, centers=3, random_state=42, cluster_std=1.2)

# ─────────────────────────────────────────
# 2. Prétraitement
# ─────────────────────────────────────────
mask = y != 2
X_bin = X[mask]
y_bin = y[mask]

scaler = StandardScaler()
X_bin_scaled = scaler.fit_transform(X_bin)

X_train, X_test, y_train, y_test = train_test_split(
    X_bin_scaled, y_bin, test_size=0.2, random_state=42
)

# ─────────────────────────────────────────
# 3. Perceptron scikit-learn (clusters 0 et 1)
# ─────────────────────────────────────────
clf = Perceptron(max_iter=100, eta0=0.01, random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("[Scikit-learn] Rapport de classification :")
print(classification_report(y_test, y_pred))
print(f"Accuracy : {accuracy_score(y_test, y_pred)*100:.2f}%")

# Frontière de décision
def plot_boundary_sklearn(model, X, y, title, filename):
    x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                         np.linspace(y_min, y_max, 200))
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
    plt.figure(figsize=(6, 4))
    plt.contourf(xx, yy, Z, alpha=0.3, cmap='bwr')
    for i, c in enumerate(['red', 'blue']):
        plt.scatter(X[y == i, 0], X[y == i, 1], c=c, edgecolors='k', label=f'Cluster {i}')
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename, dpi=100)
    plt.show()

plot_boundary_sklearn(clf, X_test, y_test,
                      "Frontière de décision - Scikit-learn",
                      "ex5_sklearn_boundary.png")

# ─────────────────────────────────────────
# 4. Segmentation avec KMeans (3 clusters)
# ─────────────────────────────────────────
X_scaled_all = StandardScaler().fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(X_scaled_all)
labels_km = kmeans.labels_

plt.figure(figsize=(6, 4))
colors = ['red', 'blue', 'green']
for i in range(3):
    plt.scatter(X_scaled_all[labels_km == i, 0],
                X_scaled_all[labels_km == i, 1],
                c=colors[i], edgecolors='k', label=f'Cluster KMeans {i}')
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', marker='X', s=200, label='Centroïdes')
plt.title("Segmentation KMeans - 3 clusters")
plt.legend()
plt.tight_layout()
plt.savefig("ex5_kmeans.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# 5. Comparaison visuelle côte à côte
# ─────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Perceptron (clusters 0 et 1)
ax = axes[0]
x_min, x_max = X_bin_scaled[:, 0].min()-0.5, X_bin_scaled[:, 0].max()+0.5
y_min, y_max = X_bin_scaled[:, 1].min()-0.5, X_bin_scaled[:, 1].max()+0.5
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                     np.linspace(y_min, y_max, 200))
Z = clf.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
ax.contourf(xx, yy, Z, alpha=0.3, cmap='bwr')
for i, c in enumerate(['red', 'blue']):
    ax.scatter(X_bin_scaled[y_bin == i, 0], X_bin_scaled[y_bin == i, 1],
               c=c, edgecolors='k', label=f'Cluster {i}')
ax.set_title("Perceptron (supervisé) - 2 clusters")
ax.legend()

# KMeans
ax = axes[1]
for i in range(3):
    ax.scatter(X_scaled_all[labels_km == i, 0], X_scaled_all[labels_km == i, 1],
               c=colors[i], edgecolors='k', label=f'Cluster {i}')
ax.scatter(centers[:, 0], centers[:, 1], c='black', marker='X', s=200, label='Centroïdes')
ax.set_title("KMeans (non supervisé) - 3 clusters")
ax.legend()

plt.suptitle("Comparaison : Perceptron vs KMeans", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("ex5_comparison.png", dpi=100)
plt.show()

print("\n--- Analyse ---")
print("Perceptron : méthode SUPERVISÉE → nécessite des étiquettes (labels).")
print("KMeans     : méthode NON SUPERVISÉE → regroupe automatiquement sans labels.")

"""Implémentation 3 — Keras

"""

"""
Exercice 5 - Implémentation KERAS
Segmentation des données synthétiques avec le Perceptron
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import tensorflow as tf
from tensorflow import keras

# ─────────────────────────────────────────
# 1. Génération des données
# ─────────────────────────────────────────
X, y = make_blobs(n_samples=300, centers=3, random_state=42, cluster_std=1.2)

plt.figure(figsize=(6, 4))
colors = ['red', 'blue', 'green']
for i in range(3):
    plt.scatter(X[y == i, 0], X[y == i, 1], c=colors[i],
                edgecolors='k', label=f'Cluster {i}')
plt.title("Données initiales - 3 clusters")
plt.legend()
plt.tight_layout()
plt.savefig("ex5_keras_data.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# 2. Prétraitement (clusters 0 et 1)
# ─────────────────────────────────────────
mask = y != 2
X_bin = X[mask]
y_bin = y[mask]

scaler = StandardScaler()
X_bin_scaled = scaler.fit_transform(X_bin)

X_train, X_test, y_train, y_test = train_test_split(
    X_bin_scaled, y_bin, test_size=0.2, random_state=42
)

# ─────────────────────────────────────────
# 3. Perceptron avec Keras
#    → Une seule couche Dense avec activation sigmoid (= Perceptron)
# ─────────────────────────────────────────
model = keras.Sequential([
    keras.layers.Input(shape=(2,)),
    keras.layers.Dense(1, activation='sigmoid')   # Perceptron simple
])

model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=0
)

# Évaluation
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n[Keras] Loss : {loss:.4f} | Accuracy : {acc*100:.2f}%")

# Courbes d'apprentissage
fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].plot(history.history['accuracy'], label='Train')
axes[0].plot(history.history['val_accuracy'], label='Validation')
axes[0].set_title("Accuracy par époque - Keras")
axes[0].set_xlabel("Époque"); axes[0].set_ylabel("Accuracy")
axes[0].legend()

axes[1].plot(history.history['loss'], label='Train')
axes[1].plot(history.history['val_loss'], label='Validation')
axes[1].set_title("Loss par époque - Keras")
axes[1].set_xlabel("Époque"); axes[1].set_ylabel("Loss")
axes[1].legend()

plt.tight_layout()
plt.savefig("ex5_keras_history.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# Frontière de décision Keras
# ─────────────────────────────────────────
x_min, x_max = X_bin_scaled[:, 0].min()-0.5, X_bin_scaled[:, 0].max()+0.5
y_min, y_max = X_bin_scaled[:, 1].min()-0.5, X_bin_scaled[:, 1].max()+0.5
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                     np.linspace(y_min, y_max, 200))
grid = np.c_[xx.ravel(), yy.ravel()]
Z = (model.predict(grid, verbose=0) >= 0.5).astype(int).reshape(xx.shape)

plt.figure(figsize=(6, 4))
plt.contourf(xx, yy, Z, alpha=0.3, cmap='bwr')
for i, c in enumerate(['red', 'blue']):
    plt.scatter(X_bin_scaled[y_bin == i, 0], X_bin_scaled[y_bin == i, 1],
                c=c, edgecolors='k', label=f'Cluster {i}')
plt.title("Frontière de décision - Keras")
plt.legend()
plt.tight_layout()
plt.savefig("ex5_keras_boundary.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# 4. KMeans (3 clusters) pour comparaison
# ─────────────────────────────────────────
X_scaled_all = StandardScaler().fit_transform(X)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(X_scaled_all)
labels_km = kmeans.labels_

plt.figure(figsize=(6, 4))
for i in range(3):
    plt.scatter(X_scaled_all[labels_km == i, 0], X_scaled_all[labels_km == i, 1],
                c=colors[i], edgecolors='k', label=f'Cluster {i}')
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', marker='X', s=200, label='Centroïdes')
plt.title("KMeans - 3 clusters")
plt.legend()
plt.tight_layout()
plt.savefig("ex5_keras_kmeans.png", dpi=100)
plt.show()

# ─────────────────────────────────────────
# 5. Analyse comparative
# ─────────────────────────────────────────
print("\n========== ANALYSE DES RÉSULTATS ==========")
print("From Scratch : implémentation manuelle, transparente mais basique.")
print("Scikit-learn : rapide, robuste, idéal pour le prototypage.")
print(f"Keras        : accuracy = {acc*100:.2f}% — flexible, extensible aux MLP.")
print()
print("Perceptron (supervisé)  : apprend une frontière linéaire à partir de labels.")
print("KMeans (non supervisé)  : regroupe automatiquement sans labels,")
print("                          cherche des centres minimisant l'inertie intra-cluster.")